using Newtonsoft.Json;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Stocks.API.ViewModels {

    /// <summary>
    /// View model that contains business errors.
    /// </summary>
    public class BusinessErrorsViewModel {

        /// <summary>
        /// Business violation codes that were generated by a request.
        /// </summary>
        [JsonPropertyName("business_errors")]
        [JsonProperty("business_errors")]
        public List<string> BusinessErrors { get; set; }

        public BusinessErrorsViewModel() {
            BusinessErrors = new List<string>();
        }
    }
}
