using Newtonsoft.Json;
using System.Collections.Generic;

namespace Stocks.API.ViewModels {

    /// <summary>
    /// View model for showing only business errors.
    /// </summary>
    public class ErrorViewModel {

        /// <summary>
        /// Business violation codes that were generated by a request.
        /// </summary>
        [JsonProperty("business_errors")]
        public List<string> BusinessErrors { get; set; }

        public ErrorViewModel() {
            BusinessErrors = new List<string>();
        }
    }
}
